### ISSUE TITLE
Add information to the Wiki

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#10]
Transcribe the information from the Google Drive folder to the GitHub Wiki for this repository. Make sure that you know Markdown so that you can format the articles well. 

I trust that you will succeed if you put your mind to it.

**Comment by rohaniru** [comment]
@Adam7557 get working on this.

**Comment by AbhinavMadahar** [comment]
This issue was moved to Charles-T-King/backend#5
