### ISSUE TITLE
Tutorials and Resources

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#10]
# Frontend Tutorials

### HTML and CSS
HTML is a markup language that contains the content of a webpage. CSS helps explain how the content should be shown, but is not needed.
* [Codecademy's Main Course](http://www.codecademy.com/skills/make-a-website)
* [Codecademy's Other Course](http://www.codecademy.com/tracks/web)

### JavaScript or JS
We will use JavaScript to make webpages interactive, but it can be used for much more.
* [Codecademy's Main Course](http://www.codecademy.com/skills/make-an-interactive-website)
* [Codecademy's Other Course](http://www.codecademy.com/tracks/javascript)

## Frameworks
Frameworks add a lot of features to a language.

### jQuery is a JS framework
jQuery is used to add effects and animations to a webpage, as well as other interactions with the page's content.
* [Codecademy's Main Course](http://www.codecademy.com/en/skills/make-an-interactive-website/topics/jquery-events/jquery-user-events)

### Bootstrap for HTML/CSS
Bootstrap makes it easy to make parts of a website like a navigation bar, a footer, a dropdown-menu, etc.
* [Codecademy's Main Course](http://www.codecademy.com/en/skills/make-a-website/topics/bootstrap-components/bootstrap-intro)

### Laravel Blade for HTML/CSS
Laravel is actually a backend framework for PHP, but it comes with Blade, which is a templating language.
* [Quick Summary](http://laravel.com/docs/5.0/templates)
* [Laracasts Video 2015](https://laracasts.com/series/laravel-5-fundamentals/episodes/5)
* [Laracasts Video 2013](https://laracasts.com/series/laravel-from-scratch/episodes/6)

**Comment by AbhinavMadahar** [comment]
I put this in README.md, so I'll close this issue now

**Comment by ChengJeremy** [comment]
Can you give a quick summary of the backend things we need to accomplish? 
Plus a general list of languages used and our goals? 
Thanks a lot 
Sorry if you have to repeat this again.

**Comment by AbhinavMadahar** [comment]
@ChengJeremy the [milestones](https://github.com/Charles-T-King/website/milestones) are the large tasks, and each milestone contains issues that talk about a smaller task. Tasks for the Backend people have the Backend label, so filter by that label to find out what Backend has to do.

At the moment, there is nothing for the Backend to do. @rvolyar or I will post some new tasks as they arrive.

**Comment by ChengJeremy** [comment]
Can you add me to the front end team again? I accidentally left it. 
I am catching up on what I missed over the last week (sorry), and Front end is doing a lot :)
