### ISSUE TITLE
Collapsing the navbar

### ISSUE THREAD

**Issue by shannonpeng** [Charles-T-King/website#12]
I played around with the window size - we're probably going to have to make the nav bar collapse at a larger size than it currently does, or delete some content off the navbar.
![screen shot 2015-03-24 at 9 24 58 pm](https://cloud.githubusercontent.com/assets/10291202/6816638/418410f0-d26c-11e4-8efa-2ca4d75d4aa8.png)
![screen shot 2015-03-24 at 9 21 02 pm](https://cloud.githubusercontent.com/assets/10291202/6816639/4188a322-d26c-11e4-91f6-7eb33fad4f6f.png)

**Comment by rvolyar** [comment]
This is just boilerplate code. We are going to remove unnecessary elements
and style the menu up.

**Comment by rvolyar** [comment]
Logo also has to be obviously bigger

**Comment by shannonpeng** [comment]
Sounds good & definitely, I'll fix that.
