### ISSUE TITLE
Chalk design

### ISSUE THREAD

**Issue by shannonpeng** [Charles-T-King/website#13]
What do you guys think of [chalk design] (https://www.google.com/search?q=chalk+artwork+on+black&es_sm=91&biw=1404&bih=718&source=lnms&tbm=isch&sa=X&ei=tgsSVY-SGcioogSW_4DQCA&ved=0CAYQ_AUoAQ#tbm=isch&q=chalk+design)? Or I guess more specifically [chalk typography] (https://www.google.com/search?q=chalk+design&es_sm=91&biw=1383&bih=718&source=lnms&tbm=isch&sa=X&ei=DBASVd6DLMSyogS1xIGYCQ&ved=0CAcQ_AUoAQ#tbm=isch&q=chalk+typography&imgdii=_).
![Example chalk art] (http://cdnimg.visualizeus.com/thumbs/6b/88/sign,typography,retro,traditional,chalk,calligraphy-6b88116c32fa53a03b60b62549b32e4c_h.jpg?ts=93246)

**Comment by rvolyar** [comment]
I like it a lot but I'm not sure it fits very well on the Web.

**Comment by shannonpeng** [comment]
I think we can try incorporating it as a creative touch, maybe - after all, chalkboards and school go hand in hand.

**Comment by AbhinavMadahar** [comment]
It might look good on the jumbotron of index.html

**Comment by shannonpeng** [comment]
@AbhinavMadahar Good idea!
