### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by ChengJeremy** [Charles-T-King/website#14]
We need a wiki

**Comment by ChengJeremy** [comment]
Transcribe the images or find the document online.

**Comment by ChengJeremy** [comment]
Appreciate the labels, Abhinav

**Comment by AbhinavMadahar** [comment]
Looks good

**Comment by ChengJeremy** [comment]
So copy over everything I did for the webpage :D  
Maybe do the source as well? I feel like the Markdown formatting is pretty decent so far.

**Comment by AbhinavMadahar** [comment]
That should be good for now
