### ISSUE TITLE
Fork & pull the original repo

### ISSUE THREAD

**Issue by rvolyar** [Charles-T-King/website#15]
Do we need to include [this](http://stackoverflow.com/questions/3903817/pull-new-updates-from-original-github-repository-into-forked-github-repository) workflow into the readme?

**Comment by rvolyar** [comment]
@AbhinavMadahar

**Comment by AbhinavMadahar** [comment]
I think I can just make a shell script that updates the fork for us

**Comment by AbhinavMadahar** [comment]
Try running ./fork-update in your local version of a fork. It should update the fork to the latest version of the original repo

**Comment by AbhinavMadahar** [comment]
Okay. It seems like everybody knows about the fork-update.sh script, so I'll close this issue
