### ISSUE TITLE
Hosting discussion 

### ISSUE THREAD

**Issue by rvolyar** [Charles-T-King/website#16]

**Comment by rvolyar** [comment]
![screenshot_2015-03-30-14-21-33](https://cloud.githubusercontent.com/assets/7801092/6903532/ef6926da-d6e8-11e4-9167-027d644810dc.png)
One obvious choice is digital ocean

**Comment by AbhinavMadahar** [comment]
I think we should do the cheapest plan they have- the [$5 plan](https://www.digitalocean.com/pricing/)- because we aren't going to need much power for the website.

**Comment by ChengJeremy** [comment]
Wow! You're amazing :D

**Comment by conorgil** [comment]
We should also consider how to protect FAFSA data if/when we store it as
part of the application submission. I'm still thinking on best approach
there, but currently considering using AWS S3 Server Side Encryption (SSE):
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

That approach will work if we host on AWS or on Digital Ocean, but wanted
to throw it out in case folks wanted to ask questions and/or start
researching potential solutions also.

On Wed, Apr 1, 2015 at 1:11 PM, Jeremy Cheng <notifications@github.com>
wrote:

> Wow! You're amazing :D
>
> On Mon, Mar 30, 2015 at 5:04 PM, Abhinav Madahar <notifications@github.com
> >
> wrote:
>
> > I think we should do the cheapest plan they have- the $5 plan
> > <https://www.digitalocean.com/pricing/>- because we aren't going to need
> > much power for the website.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Charles-T-King/website/issues/16#issuecomment-87831228>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Charles-T-King/website/issues/16#issuecomment-88557373>
> .
>



-- 
Conor Gilsenan
conorgilsenan@gmail.com
973-986-6650 (cell)

**Comment by AbhinavMadahar** [comment]
We should discuss this at the very end.
