### ISSUE TITLE
Decide on Design Principles

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#3]
In the comments, please describe what you think about the following issues.

#### Tabs or Spaces for Indentation
And if spaces are better, should we use 2, 4, or 8?

# What Language to use for...

### Backend
* PHP with Laravel
* Python with Django
* Ruby on Rails

### Frontend
* Javascript
* CoffeeScript
* Dart

**Comment by shannonpeng** [comment]
**Tabs or Spaces:** Tabs
**Backend:** I think PHP since we've been learning it, but I also want to learn Rails
**Frontend:** Javascript
**Frameworks:** Why not all three? Although I've never used the first before

**Comment by AbhinavMadahar** [comment]
@shannonpeng Rails might be somewhat harder than PHP or Django.

**Comment by AbhinavMadahar** [comment]
Also, the final section about what frameworks to use is redundant, so I'll remove it

**Comment by shannonpeng** [comment]
@AbhinavMadahar okay PHP it is then lol

**Comment by AbhinavMadahar** [comment]
We're going to use Laravel on PHP since that seems to be the increasing in popularity.

**Comment by serialscoper101** [comment]
To clarify, we are going to talk to Conor and see his thoughts on this. I'm very leaning to Laravel though since I'm experienced in it and I think it's the easiest to learn.

**Comment by AbhinavMadahar** [comment]
@serialscoper101 do you know Conor's GitHub username? It would be useful if we added him to the organization

**Comment by serialscoper101** [comment]
@conorgil I think

**Comment by conorgil** [comment]
@AbhinavMadahar  @serialscoper101 @shannonpeng Yup, my github name is @conorgil. Good sleuthing. Is it possible to chat tomorrow (Friday) to get organized and talk through some things? If that is too short notice, then let's figure out a time early next week. Progress looks great so far on the logo, getting this Github org setup, discussing frameworks, etc!

**Comment by AbhinavMadahar** [comment]
Looks like we have a general idea of all the frameworks and other things we will use, so I'll close this issue.

If anyone wants to talk about a specific framework or something like that, please make a new issue for that topic.
