### ISSUE TITLE
Install MySQL on Windows

### ISSUE THREAD

**Issue by ChengJeremy** [Charles-T-King/website#35]
Watch [this video](https://www.youtube.com/watch?v=3jVjnGkPsRg)

Mac users: shouldn't be too bad for you guys; the process is much the same :D

**Comment by rvolyar** [comment]
@Charles-T-King/backend

**Comment by ChengJeremy** [comment]
My video was watched in Russia.

**Comment by AbhinavMadahar** [comment]
Everyone should have installed by now
