### ISSUE TITLE
Homepage discussion

### ISSUE THREAD

**Issue by 16yildiza** [Charles-T-King/website#37]
Picture
Tagline
Testimonials/Success stories
About
Apply for a loan
Contact

**Comment by rvolyar** [comment]
Here's a sample bootstrap landing page template that sort of fits the sections/layout we want.
http://ironsummitmedia.github.io/startbootstrap-landing-page/

**Comment by AbhinavMadahar** [comment]
This is a duplicate of issue #5 so please put the discussion in there
