### ISSUE TITLE
Install Backend Requirements for SASS

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#38]
This is a backend issue because it's about the server. **The Frontend people cannot use SASS until you finish this**. Please make a pull request upon completion. Also, this does not need to be handled by everyone, so just have 1 or 2 people work on this. This should hopefully only take a few days or less.

@Charles-T-King/backend hopefully [this tutorial](https://medium.com/@dvabr/laravel-with-bootstrap-sass-4512cf992d0c) will help.

You must install and configure NPM, Bower, and Grunt so that the server can convert the SASS files into CSS files. You do not need to worry about the contents of the SASS and CSS files- just make it so that the server can convert all the files in a SASS folder to CSS in a CSS folder.

**Comment by ChengJeremy** [comment]
I will try to decrypt this email and convey the message to the back end
people; Russ might need to help :D

**Comment by rvolyar** [comment]
Maybe we can use laravel's [Elixir](http://laravel.com/docs/5.0/elixir) for this.

"Laravel Elixir provides a clean, fluent API for defining basic Gulp tasks for your Laravel application. Elixir supports several common CSS and JavaScript pre-processors, and even testing tools."

**Comment by ChengJeremy** [comment]
I'll look into that.

**Comment by AbhinavMadahar** [comment]
@ChengJeremy Bootstrap is only for frontend, so you don't have to learn it

**Comment by ChengJeremy** [comment]
ok

**Comment by AbhinavMadahar** [comment]
We'll just use pure CSS for now
