### ISSUE TITLE
Make a Template

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#4]
### Using Laravel's [Blade](http://laravel.com/docs/5.0/templates), make a standard template that has:
* A static (i.e. not changing) navigation bar
* A content section that can be changed in each file
* A static footer

**Comment by rvolyar** [comment]
Maybe static instead of non-changing?

**Comment by AbhinavMadahar** [comment]
@rvolyar corrected

**Comment by AbhinavMadahar** [comment]
Issue #11 completed this, so I'll close this issu
