### ISSUE TITLE
Next Meeting with Charles T. King

### ISSUE THREAD

**Issue by rvolyar** [Charles-T-King/website#43]
Lauren emailed me back saying she could meet anytime next week except Tuesday after school to talk and answer questions about CTK.  What days are you, those who would like to meet available? @Charles-T-King/frontend @Charles-T-King/backend Please post below.

**Comment by AbhinavMadahar** [comment]
Answer it in [this Google Form](https://docs.google.com/forms/d/1adf8g0hUiIJ86ahnBv9kKHq1AaZVuj7TOMBbhzbX_WA/viewform?usp=send_form) ASAP so that we can schedule it.

**Comment by AbhinavMadahar** [comment]
Here are the results:
![Results](https://chart.googleapis.com/chart?cht=bhs&chs=345x150&chbh=24%2C6&chxt=x%2Cy&chxl=0%3A%7C0%7C1%7C2%7C3%7C4%7C5%7C1%3A%7CFriday%20April%2024%7CThursday%20April%2023%7CWednesday%20April%2022%7CMonday%20April%2020&chds=0%2C5&chco=0000e0&chxs=0%2C000000%2C12%2C0%2Clt%7C1%2C000000%2C12%2C1%2Clt&chd=t%3A3%2C4%2C3%2C5)

**Comment by AbhinavMadahar** [comment]
So we'll do it on Friday after school then.
