### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#44]
@Charles-T-King/backend we may have a major security flaw if you don't know about this stuff.

[This Computerphile video](https://youtu.be/_jKylhJtPmI) is a really good summary of SQL Injection. The major danger with SQL Injections is that they could let someone open the database and see others' data like passwords, bank account info., etc.

At some point before you put the SQL database into staging, make sure that you **REMEMBER TO STOP SQL INJECTIONS**

**Comment by rvolyar** [comment]
Beauty of laravel is that it strips data so can never be performed.

**Comment by rvolyar** [comment]
But this is still good to know
