### ISSUE TITLE
What Back End needs to do

### ISSUE THREAD

**Issue by ChengJeremy** [Charles-T-King/website#45]
Watch videos on Laravel: https://laracasts.com/series/laravel-5-fundamentals 

Ok so the whole purpose of mySQL during this project was just for learning and database familiarization?
So everything will be on C9 now, right? 

:D Anyways, bottom line is that we should all just learn Laravel and come all prepared on Funday Monday for anything.

**Comment by AbhinavMadahar** [comment]
MySQL is a SQL database. You were using a GUI for it, and you will continue to use it but via a CLI
