### ISSUE TITLE
Accept POST Requests

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#46]
@Charles-T-King/backend 

Requirements
------------------
You need to make the server accept POST requests on ```/apply/create``` and add the contents to a database.

Tutorials
-----------
Of course, you need to learn how to make a database first by watching the videos in #62 

Timeframe
-------------
This will be the first thing that the backend people do for Milestone 2

**Comment by rvolyar** [comment]
Ajax is unnessasary since we are not making a single page app.  While you can make Laravel work with AJAX, it is much better to use separate pages and the functions Laravel provides for different tasks.

**Comment by AbhinavMadahar** [comment]
@rvolyar AJAX isn't just for single-page websites, and it's perfectly easy to use on Laravel. Besides, it's easier for the frontend people to just send an AJAX request and not have to deal with multiple pages.
