### ISSUE TITLE
Add New Applicants to Database

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#47]
@Charles-T-King/backend before you do this, make sure that #46 is complete.

Requirements
------------------
Make it so that, after getting a POST request, the contents of the request are processed and added to a SQL database of applicants.

Timeframe
-------------
This is the final part of the backend side for Milestone 2, so it should be completed a few days before Milestone 2 is due to allow for testing before putting it in production.

**Comment by rvolyar** [comment]
Before this is done, we need to model our database schema.

**Comment by ChengJeremy** [comment]
I have SQL working on my laptop, so I'll definitely bring that in next week; This week, we're just watching Laravel videos. 

Also, as a side question, can we still run the update.sh file on c9?

Lastly, Abhinav just unassigned something to me, so for now, is there anything you guys can think of that needs doing? If not, I will just do whatever presents itself as necessary to be done later then. I will attend the meeting, and I think we should take notes there. (It is on Friday, right?)

**Comment by ChengJeremy** [comment]
One question: So we can create out entire database on c9, right?

How does mySQL come into play? (if it has no other purpose than for
practice, then... it's kind of... yeah)

**Comment by rvolyar** [comment]
MySQL is the actual database.  You can make [migrations](http://daylerees.com/codebright/migrations) in laravel and run them, which would create the tables in MySQL on c9.
