### ISSUE TITLE
Make an Apply Page

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#48]
@Charles-T-King/frontend this is for you.

Requirements
===========
* Must use the default template
* Must have places to put the applicant's name, address, phone number, etc.

HTML Elements and Names
-----------------------------------
Because someone else will be making the AJAX for your page, add the following id to the appropriate element:
#### Forms
* 'first-name'
* 'last-name'
* 'middle-initial'
* etc
Look in the Google Drive folder for the 'Application.pdf' file and make sure there is a form to put in everything. Comment below what the IDs will be.

Timeframe
-------------
ASAP so that we can integrate AJAX with it.

**Comment by rvolyar** [comment]
Let's think about stage 2 when we are done with the first one. Sounds good?

**Comment by AbhinavMadahar** [comment]
@rvolyar about half of the people in the frontend are done with Milestone 1

**Comment by rvolyar** [comment]
We have to talk with CTK and Conor about how we are going to proceed with the future steps before making any commitments.

**Comment by rvolyar** [comment]
New instructions:
1. No dynamic/ajax forms are needed for the current static site
2. Only list instructions and links to the forms needed to fill out to apply (offline). These are available on google drive.
3. Make sure to upload the forms to our laravel site. Probably make a folder in the resources folder.

**Comment by AbhinavMadahar** [comment]
Newer instructions:
* Add forms to enter information
* Make it so that, after pressing a ```Print``` button, ```window.print()``` is called to print the page
That way, the applicant can physically send their form

**Comment by ChengJeremy** [comment]
ok

**Comment by rvolyar** [comment]
Isn't the file a pdf which the user can print themselves?

**Comment by ChengJeremy** [comment]
ok

**Comment by rvolyar** [comment]
Ok what?

**Comment by AbhinavMadahar** [comment]
@rvolar this way it's easier for the person if they want to type it out.
