### ISSUE TITLE
Rename 'master' to 'production'

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#49]
'Production' refers to the version of the software that is released to common users- in web development, it would be the website that people see when going to [charlestking.org](http://charlestking.org)

However, git by sets the default branch's name to 'master' for simplicity. I think we should rename the master branch to 'production' since that's the most reflective of the branch's use, and we already have an issue for 'environment:production' and we cannot call it 'environment:master' because that doesn't make sense.

What do you all think? @Charles-T-King/backend @Charles-T-King/frontend

**Comment by rvolyar** [comment]
Will this break git somehow on their local machines?

**Comment by AbhinavMadahar** [comment]
@rvolyar it makes the most sense to just delete the master branch and make a new production branch when we finish Milestone 1. After that, a simple ```git pull``` will update everyone so they have the production branch.

**Comment by AbhinavMadahar** [comment]
Once milestone/2 is fully tested and confirmed, we will make a new branch out of it called 'production'
