### ISSUE TITLE
Make a Homepage

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#5]
Use the template that was made in issue #4 to make a homepage.

# Requirements

* Must have the logo we made for Charles T. King
* Must have a few important links on the jumbotron
* Must use the template we made earlier
* Must give a very brief description/summary of Charles T. King

**Comment by AbhinavMadahar** [comment]
@DelgadoFukushima is doing this with @vikrantmisra

**Comment by rvolyar** [comment]
Any updates @DelgadoFukushima @vikrantmisra ?

**Comment by AbhinavMadahar** [comment]
They said that they were about halfway done, I think.

**Comment by rvolyar** [comment]
Can you make a pull request to the main repo with homepage? @DelgadoFukushima @vikrantmisra

**Comment by rvolyar** [comment]
New homepage discussins will be here
@16yildiza 

Picture
Tagline
Testimonials/Success stories
About
Apply for a loan
Contact

**Comment by AbhinavMadahar** [comment]
They are now redesigning it

**Comment by 16yildiza** [comment]
Envelope: http://fortawesome.github.io/Font-Awesome/icon/envelope-o/

**Comment by shannonpeng** [comment]
http://www.cssdesignawards.com/articles/round-up-38-neat-css-js-hover-effects/101/

**Comment by 16yildiza** [comment]
Apply (White): http://fortawesome.github.io/Font-Awesome/icon/paper-plane-o/
Apply (Black): http://fortawesome.github.io/Font-Awesome/icon/paper-plane/

**Comment by 16yildiza** [comment]
Check status: http://fortawesome.github.io/Font-Awesome/icon/check-square-o/

**Comment by 16yildiza** [comment]
Bar chart: http://fortawesome.github.io/Font-Awesome/icon/bar-chart/

**Comment by 16yildiza** [comment]
![home page](https://cloud.githubusercontent.com/assets/11217269/7188312/bec4d952-e444-11e4-97da-a34d5cd28aa5.JPG)

**Comment by shannonpeng** [comment]
A live demo of what I sort of had in mind :) (we can work on the hover effects later witht he other examples I showed you guys) http://codepen.io/shannonpeng/pen/wawqyX

**Comment by AbhinavMadahar** [comment]
@shannonpeng I think it looks good

**Comment by AbhinavMadahar** [comment]
Instead of having everyone work on the homepage, how about Vikrant just makes a simple one now and everyone else works on other things. When the rest of the website is done, we will fill out the homepage and talk about all the different things you can do on the website.

**Comment by shannonpeng** [comment]
What should everyone else do in the meanwhile?

**Comment by AbhinavMadahar** [comment]
@shannonpeng you all are assigned to an issue

**Comment by AbhinavMadahar** [comment]
Merge #60 finished the homepage for now
