### ISSUE TITLE
Meeting summary is now up.

### ISSUE THREAD

**Issue by serialscoper101** [Charles-T-King/website#6]
Check the readme file in this repo for a link to a drive folder with all of our discussion's with Conor and Charles T. King

For the lazy - 
[Drive Folder](https://drive.google.com/folderview?id=0BxEuMs2jIxWfV0VNQ1ZzZFJpUkU&usp=drive_web)

**Comment by 16yildiza** [comment]
So, question... are we gonna meet with Conor as a group again? If so, I have some questions I would like to ask him about the interface/design/theme of the overall website.

**Comment by serialscoper101** [comment]
Conor's leaving on break soon but I think him, Abhinav and I will meet before then so you can leave your questions with me and I'll pass them on.

**Comment by AbhinavMadahar** [comment]
Looks like everyone has read it, so I'll close it, and we can just have a link in the README.md
