### ISSUE TITLE
Make an About Page

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#6]
Use the template that was made in issue #4 to make an About Us page

# Requirements

* Must give a detailed description of Charles T. King
* Must have a few pictures of the volunteers/employees at Charles T. King
* Does not have to give contact information

**Comment by kaylawolf** [comment]
Izzy and I are on the job

**Comment by AbhinavMadahar** [comment]
Issue #19 is a pull request involving this. @izzywtt7 made ab about.blade.php file, but not the stuff inside yet.

**Comment by ChengJeremy** [comment]
I'll transcribe everything over if I have the time. However, the wiki is
open for everybody, and you all have access to the shared documents. Good
luck!

**Comment by AbhinavMadahar** [comment]
@kaylawolf @izzywtt7 how's the progress?

**Comment by ChengJeremy** [comment]
You can paste over everything on the wiki.

**Comment by rvolyar** [comment]
We have a simple about page done. Will reopen when needed
