### ISSUE TITLE
Videos for backend to watch

### ISSUE THREAD

**Issue by ChengJeremy** [Charles-T-King/website#62]
This is for @Charles-T-King/backend
Watch all laracasts: https://laracasts.com/series/laravel-5-fundamentals 

Means to spread out 5.73 hours over the week

Please don't close this issue until at least a few days later, @AbhinavMadahar. We know our jobs. :D 
We need to stay focused as much as possible during classes this week!

**Comment by AbhinavMadahar** [comment]
This is definitely not a priority:extreme

**Comment by AbhinavMadahar** [comment]
What episode are most of you all on?

**Comment by AbhinavMadahar** [comment]
You should all watch episodes:
* [8](https://laracasts.com/series/laravel-5-fundamentals/episodes/8#)
* [10](https://laracasts.com/series/laravel-5-fundamentals/episodes/10#)
* [12](https://laracasts.com/series/laravel-5-fundamentals/episodes/12)
* [15](https://laracasts.com/series/laravel-5-fundamentals/episodes/15#)

**Comment by ChengJeremy** [comment]
Videos to watch: 6-15

**Comment by ChengJeremy** [comment]
HOW TO CREATE A DATABASE TABLE USING LARAVEL::: 
http://laravel.com/docs/4.2/schema

**Comment by ChengJeremy** [comment]
MIGRATIONS::: 
http://laravel.com/docs/4.2/migrations
