### ISSUE TITLE
Questions to ask Charles T. King people

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#65]
For the meeting we are having on Friday, what questions should we ask? Put it in the comments below

**Comment by AbhinavMadahar** [comment]
_What should the colour scheme be?_

**Comment by AbhinavMadahar** [comment]
_What time of the year do you get the most applications?_
That way, we know when we need to finish Milestone 2

**Comment by 16yildiza** [comment]
Questions for 
Charles T. King
Meeting of 4/24/15
Frontend: Asena Yildiz, Vikrant Misra, Shannon Peng, Marcela Delgado-Fukushima
1.	What should the color scheme be?

2.	How many people apply?

3.	When do people apply?

4.	Can we have pictures of students, success stories, and the organization, and its specific members?

5.	Can we have important member specifics (Director/President/CEO/etc.)?

6.	Can we be provided approved testimonials?

7.	Could we be provided with the information you specifically want us to put on the about page, home page, etc. (typed up paragraph)?

8.	What mood/feel are you looking for in the website?

**Comment by shannonpeng** [comment]
![questions](https://cloud.githubusercontent.com/assets/10291202/7304424/5e46d0b8-e9c5-11e4-9126-a1e13fde9961.jpg)

**Comment by AbhinavMadahar** [comment]
They like the colour scheme.

They can take a picture of the board of trustees next month.

#### They want the following pages
* FAQ and clear general questions
* Donate

**Comment by AbhinavMadahar** [comment]
They usually get 10 to 15 applications per year

**Comment by AbhinavMadahar** [comment]
The traffic comes from the end of April to sometime in May

**Comment by AbhinavMadahar** [comment]
They are okay with using charlestking.org
