### ISSUE TITLE
Problems with css

### ISSUE THREAD

**Issue by rvolyar** [Charles-T-King/website#68]
While making the apply page, I noticed a lot of problems with the css that was written for the homepage.  I will just list out any of them that catch my eye.  If you're unsure about any, google them

1. Never use !important
2. Never use id's to target html in css. Use classes
3. Use a good naming structure( don't name a class pizza when pizza has nothing to do with it. This makes it hard for others to understand what you are doing
4. Make sure that you are targeting your html very specifically. For example, I wanted to use an h3 on the apply page, but it was colored white on a white background because this fit the homepage, but not my apply page.

@vikrantmisra 
@shannonpeng 
@Charles-T-King/frontend

**Comment by AbhinavMadahar** [comment]
Definitely. Also, make sure that _your_ stylesheet is linked at the end so that it automatically overrides the Bootstrap and other CSS without needed an important tag. 

That said, there are [some places](https://css-tricks.com/when-using-important-is-the-right-choice/) where important is useful, but they're very rare.

**Comment by shannonpeng** [comment]
The homepage isn't supposed to be final as of now (thus the .pizza), but I'll fix the !important and h3. What's wrong with ID's if you only want to target one item on the page? It's good to know for sure that it refers to one thing only.

**Comment by AbhinavMadahar** [comment]
@shannonpeng it's really just a mindset convention. Usually, an ID is for selecting the content for manipulating the content, and a class is for selecting the content for manipulating how it looks. Also, things should look alike, so changing the appearance of just 1 element can result in it looking different from the rest

**Comment by shannonpeng** [comment]
Oh that makes sense. I'm used to looking at classes and instantly thinking
"this might apply to more than one element". Sometimes you do want specific
elements distinguished from others, though, like the case in which I used
both a class and IDs: adding the .section class to each section on the
homepage but using different ID's to apply a different background color to
each of them. Unless that's what you guys wanted to change.
