### ISSUE TITLE
Make a Homepage

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#7]
### Fork this Repo
1. Fork this repo
2. Make changes to your fork
3. Make a pull request
It would be best to make changes on Cloud9, but that's your prerogative.

**We will decide as a group on who has the best**

# Requirements for the homepage
* Have the logo that Shannon and Asena made
* Make the favicon the icon that they made

### Make sure that there is a navigation bar that links to them but have say the following pages:

* About
* Contact Us
* Apply for a loan

**NONE OF THESE PAGES WILL BE MADE!** You are just linking to the page but not making it yet.

**Comment by AbhinavMadahar** [comment]
I made a fork request for the version with a navigation bar on top: #8

**Comment by AbhinavMadahar** [comment]
I think I can actually use jQuery to make a navigation bar, which would allow us to make the same navigation bar on all the pages automatically. Here's the [thread](https://stackoverflow.com/questions/8988855/include-another-html-file-in-a-html-file) I found it on.

**Comment by serialscoper101** [comment]
Its better to use blade templates in laravel. They were made for this.

**Comment by serialscoper101** [comment]
http://laravel.com/docs/5.0/templates
Here are the docs

**Comment by AbhinavMadahar** [comment]
This issue was moved to Charles-T-King/backend#6
