### ISSUE TITLE
Make a Contact Page

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#7]
Use the template that was made in issue #4 to make a Contact Us page.

# Requirements
List all the different ways to contact Charles T. King (the info is in Google Drive folder)
* Have email links
* Have phone numbers
* Embed Google Maps so that they can see where the organization is located

**Comment by rvolyar** [comment]
isn't their location a po box?

**Comment by AbhinavMadahar** [comment]
@rvolyar I think so, but the Ed Center is where they are located- I think

**Comment by AbhinavMadahar** [comment]
@shannonpeng is doing this with @16yildiza

**Comment by AbhinavMadahar** [comment]
They are now done with this
