### ISSUE TITLE
Css problems

### ISSUE THREAD

**Issue by rvolyar** [Charles-T-King/website#76]
A couple things to note
1. There should be one styles.css file pertaining to all pages, not separate ones for each different page.
2. The heading is now moved because of the change of class on the about page

**Comment by rvolyar** [comment]
@Charles-T-King/frontend 
@16yildiza

**Comment by AbhinavMadahar** [comment]
@rvolyar I told them to have CSS for the different pages because we are going to do a lot of designing with CSS, and having just 1 stylesheet will cause it to become gigantic.

**Comment by rvolyar** [comment]
What about point number two?

**Comment by AbhinavMadahar** [comment]
@rvolyar we will fix that tomorrow
