### ISSUE TITLE
An interesting website layout

### ISSUE THREAD

**Issue by ChengJeremy** [Charles-T-King/website#77]
I found this pretty cool website layout for Great Lakes student loan that we could draft some ideas off of. (There's a lot of images!)

https://www.mygreatlakes.org/ 

so click on the link and check it out! Maybe it will help. 
@AbhinavMadahar 
@16yildiza 

And backend! Check it out if you have 30 seconds. It can't hurt. 
@rvolyar 
@amar116 
@harryharpel 
@k-hubert15 

Also, I really like our website theme and layout so far :D

**Comment by rvolyar** [comment]
Looks interesting!

**Comment by ChengJeremy** [comment]
https://laracasts.com/series/laravel-5-fundamentals/episodes/15

**Comment by ChengJeremy** [comment]
https://laracasts.com/series/laravel-5-fundamentals/episodes/16

**Comment by AbhinavMadahar** [comment]
@ChengJeremy don't put those videos in this thread. Doing such is very off-topic and makes the thread disorganized.
