### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/website#9]
@shannonpeng @16yildiza I know you 2 enjoy color schemes, so can you 2 figure out what color schemes we should do? [This list](http://www.dtelepathy.com/blog/inspiration/beautiful-color-palettes-for-your-next-web-project) looks nice.

**Comment by shannonpeng** [comment]
@AbhinavMadahar I like 1, 6, and 22!

**Comment by rvolyar** [comment]
We need to choose around 3 colors on which we will base the design off.  [Color lovers](http://www.colourlovers.com/palettes) has searchable palettes.  I also like [Paletton](http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF)  to design my color schemes.

**Comment by rvolyar** [comment]
I like this one.
<a href="http://www.colourlovers.com/palette/1306808/Educational_Corner?widths=1" target="_blank"><img src="http://www.colourlovers.com/images/badges/pw/1306/1306808_Educational_Corner.png" style="width: 240px; height: 120px; border: 0 none;" alt="Educational_Corner" /></a><br /><span style="font-size: 10px; color: #5e5e5e;"><a href="http://www.colourlovers.com/color" target="_blank" style="font-size: 10px; color: #5e5e5e;">Color</a> by <a href="http://www.colourlovers.com/" target="_blank" style="font-size: 10px; color: #5e5e5e;">COLOURlovers</a></span>

**Comment by shannonpeng** [comment]
I like that too - and it's appropriately named!
We might have to change the logo if we use that though. Any news on which logo is approved?

**Comment by rvolyar** [comment]
Not yet. Can you make another version of the logo with this palette?

**Comment by AbhinavMadahar** [comment]
Educational Corner looks good to me as well

**Comment by AbhinavMadahar** [comment]
Do we have a somewhat final idea?

**Comment by AbhinavMadahar** [comment]
They liked the current one
